export const criminallawdata = [
  "· Assault Crimes ",
  "· Assault with a Deadly Weapon ",
  "· Assaulting a Police Officer ",
  "· Alcohol & Beverage Control Violations ",
  "· Addiction / Substance Abuse ",
  "· Attempted Murder ",
  "· Auto Burglary ",
  "· Building Code Violations ",
  "· Brandishing a Weapon ",
  "· Burglary ",
  "· Cannabis Law ",
  "· Corporate Crime / Regulatory Offenses ",
  "· Corporal Injury to Spouse ",
  "· Criminal Appeals ",
  "· Criminal Threats ",
  "· Domestic Battery ",
  "· Domestic Violence ",
  "· Drug Crime ",
  "· Drug Possession ",
  "· Drug Possession For Sale ",
  "· DUI Causing Injury ",
  "· DUI Defense ",
  "· Embezzlement ",
  "· Federal Crimes ",
  "· Felony Hit and Run ",
  "· Firearm Violations ",
  "· Fire Code Violations ",
  "· Grand Theft Auto ",
  "· Grand Theft ",
  "· Hit and Run ",
  "· Human Trafficking ",
  "· Insurance Fraud ",
  "· Juvenile Crimes ",
  "· Prescription Drug Fraud ",
  "· Pre-Filing Representation ",
  "· Prostitution ",
  "· Probation Violations ",
  "· Resisting Arrest ",
  "· Restraining Orders ",
  "· RICO cases ",
  "· Robbery ",
  "· Sex Crimes ",
  "· Shoplifting ",
  "· Theft Crimes ",
  "· Trespassing ",
  "· Violent Crimes ",
  "· White Collar Crimes",
];
